"""vLLM logits processor for the bytes decoder: only bytes continuing valid UTF-8, and words end (EOS, or at
max_tokens) only at character boundaries."""
import torch
from vllm.v1.sample.logits_processor import BatchUpdate, LogitsProcessor
from vllm.v1.sample.logits_processor.builtin import process_dict_updates


def utf8_transitions() -> torch.Tensor:
    """(8, 256) UTF-8 decoder state after each byte, -1 where the byte is invalid.
    State 0: at a character boundary. 1-3: that many continuation bytes (80-BF) left.
    4-7: after E0, ED, F0, F4, whose next byte has a narrower range (no overlong encodings, surrogates, > U+10FFFF)."""
    table = torch.full((8, 256), -1, dtype=torch.long)
    table[0, :0x80] = 0
    table[0, 0xC2:0xE0] = 1
    table[0, 0xE0:0xF0] = 2
    table[0, 0xF0:0xF5] = 3
    table[0, [0xE0, 0xED, 0xF0, 0xF4]] = torch.tensor([4, 5, 6, 7])
    for state, (low, high, after) in {1: (0x80, 0xC0, 0), 2: (0x80, 0xC0, 1), 3: (0x80, 0xC0, 2),
                                      4: (0xA0, 0xC0, 1), 5: (0x80, 0xA0, 1),
                                      6: (0x90, 0xC0, 2), 7: (0x80, 0x90, 2)}.items():
        table[state, low:high] = after
    return table


class UTF8LogitsProcessor(LogitsProcessor):
    """Prompts (BOS and a prefix of whole characters) end at a character boundary, so each request's state only
    depends on its generated bytes."""

    def __init__(self, vllm_config, device: torch.device, is_pin_memory: bool):
        transitions = utf8_transitions()
        self.transitions = transitions.tolist()
        # Continuation bytes still needed after each byte (in each state), more than any request has if invalid
        needed = torch.tensor([0, 1, 2, 3, 2, 2, 3, 3, 2**20])[transitions]
        self.needed = needed.to(device)
        self.requests: dict[int, list] = {}  # Batch index -> [state, output token ids (live), consumed, max_tokens]

    def is_argmax_invariant(self) -> bool:
        return False

    def update_state(self, batch_update: BatchUpdate | None):
        process_dict_updates(self.requests, batch_update,
                             lambda params, prompt, output: [0, output, 0, params.max_tokens or 2**20])

    def apply(self, logits: torch.Tensor) -> torch.Tensor:
        if not self.requests:
            return logits
        states = torch.zeros(len(logits), dtype=torch.long)
        remaining = torch.full((len(logits),), 2**20)
        for index, request in self.requests.items():
            # The last sampled byte is appended to the (live) output after update_state, so states advance here
            state, output, consumed, max_tokens = request
            for token in output[consumed:]:
                state = max(self.transitions[state][token], 0)  # Recover from an invalid byte (not sampled)
            request[0], request[2] = state, len(output)
            states[index], remaining[index] = state, max_tokens - len(output) - 1  # Tokens after this one
        device = self.needed.device
        allowed = self.needed[states.to(device)] <= remaining.to(device)[:, None]
        logits[:, :256].masked_fill_(~allowed, float("-inf"))
        return logits
