name: 'Setup Environment'
description: 'Install rendering dependencies, setup uv, and install Python dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

runs:
  using: 'composite'
  steps:
    - name: Set up Pango and Cairo
      uses: sign/pixel-renderer/.github/actions/setup-pango-cairo@main

    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: true
        activate-environment: true

    - name: Install dependencies
      shell: bash
      run: uv pip install ".[dev,train]"

