output_dir: /tmp/welt-bench

model:
  bytes_encoder: welt_training/experiments/models/bytes-encoder-tiny.json
  latent_transformer: welt_training/experiments/models/latent-70m.json
  bytes_decoder: sbintuitions/tiny-lm

data:
  dataset_name: Helsinki-NLP/opus-100
  dataset_config_name: en-he
  dataset_text_template: "<en>\x0E{translation[en]}\x0F<he> {translation[he]}"
  seq_length: 128
  max_word_length: 32
  max_eval_samples: 64
  num_workers: 8

train:
  train_iters: 300
  micro_batch_size: 32
  global_batch_size: 32

optimizer:
  lr: 3.0e-4

validation:
  eval_interval: 1000
  eval_iters: 0

checkpoint:
  save_interval: null
  save: null
  load: null

logger:
  log_interval: 10
